// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsOehGBjSOR-jPclycFkvvWhWJQxUHI44',
    appId: '1:199740691166:web:0a8ef6f7b5db051a7f284f',
    messagingSenderId: '199740691166',
    projectId: 'scry-74d26',
    authDomain: 'scry-74d26.firebaseapp.com',
    storageBucket: 'scry-74d26.appspot.com',
    measurementId: 'G-6QWEFZD9LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtTq-NTfTF5cLBJQIzNicXfOloqPTWoA',
    appId: '1:199740691166:android:b3d3dd079005d9257f284f',
    messagingSenderId: '199740691166',
    projectId: 'scry-74d26',
    storageBucket: 'scry-74d26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoQNPNU7dYSV087QL3GKsQXOruHEJOwko',
    appId: '1:199740691166:ios:54d530496173509d7f284f',
    messagingSenderId: '199740691166',
    projectId: 'scry-74d26',
    storageBucket: 'scry-74d26.appspot.com',
    iosClientId: '199740691166-4ekh7ijbgani81mu8um807lgueu2mjel.apps.googleusercontent.com',
    iosBundleId: 'com.example.scry',
  );
}
